Architecture:
  Decoder:
    c_decoder:
      ctc_decoder:
        infer_quality: false
        inner_decoder:
          name: RCTCDecoder
        max_len: 25
        name: QualityWrapperDecoder
      detach: false
      gtc_decoder:
        ds: true
        max_len: 25
        name: SMTRDecoder
        next_mode: true
        num_layer: 1
        sub_str_len: 5
      infer_gtc: true
      name: GTCDecoder
    g_decoder:
      ctc_decoder:
        infer_quality: false
        inner_decoder:
          name: RCTCDecoder
        max_len: 75
        name: QualityWrapperDecoder
      detach: false
      gtc_decoder:
        ds: true
        max_len: 75
        name: SMTRDecoder
        next_mode: true
        num_layer: 1
        sub_str_len: 15
      infer_gtc: true
      name: GTCDecoder
    name: GCHDecoder
    use_c: true
    use_g: false
  Encoder:
    depths:
    - 6
    - 6
    - 6
    dims:
    - 128
    - 256
    - 384
    feat2d: true
    last_stage: false
    local_k:
    - - 5
      - 5
    - - 5
      - 5
    - - -1
      - -1
    mixer:
    - - Conv
      - Conv
      - Conv
      - Conv
      - Conv
      - Conv
    - - Conv
      - Conv
      - FGlobal
      - Global
      - Global
      - Global
    - - Global
      - Global
      - Global
      - Global
      - Global
      - Global
    name: SVTRv2LNConvTwo33
    num_heads:
    - 4
    - 8
    - 12
    sub_k:
    - - 1
      - 1
    - - 2
      - 1
    - - -1
      - -1
    use_pos_embed: false
  Transform: null
  algorithm: SVTRv2
  in_channels: 3
  model_type: rec
  name: GCHRecognizer
Eval:
  dataset:
    data_dir_list:
    - /home/resources/shared_datasets/STR/aihub_rec
    ds_width: true
    label_file_list:
    - /home/resources/gch/1_datasets/1_AIHUB/2_split_horizontal_clean_80:10:10/1_train/1_main___id_14/label.txt
    name: SimpleDatasetTVResize
    padding: false
    transforms:
    - DecodeImagePIL:
        img_mode: RGB
    - GCHLabelEncode:
        c_encoder:
          character_dict_path: /home/resources/gch/2_charsets/2_group/gch/C_all___id_50/charset.txt
          ctc_label_encode:
            inner_encoder:
              name: CTCLabelEncode
            name: QualityWrapperHeadLabelEncode
          gtc_label_encode:
            name: ARLabelEncode
          lower: true
          max_text_length: 25
          name: GTCLabelEncode
          use_space_char: false
        g_encoder:
          character_dict_path: /home/resources/gch/2_charsets/2_group/gch/G_all___id_51/charset.txt
          ctc_label_encode:
            inner_encoder:
              name: CTCLabelEncode
            name: QualityWrapperHeadLabelEncode
          gtc_label_encode:
            name: ARLabelEncode
          lower: true
          max_text_length: 75
          name: GTCLabelEncode
          use_space_char: false
        use_c: true
        use_g: true
    - HierarchyKeepKeys:
        keep_keys:
          c_label:
            ctc_label:
              inner_label:
                label: null
                length: null
              quality_label: null
            gtc_label:
              label: null
              length: null
          g_label:
            ctc_label:
              inner_label:
                label: null
                length: null
              quality_label: null
            gtc_label:
              label: null
              length: null
          image: null
  loader:
    batch_size_per_card: 512
    drop_last: false
    max_ratio: 12
    num_workers: 0
    shuffle: false
  sampler:
    divided_factor:
    - 4
    - 16
    first_bs: 128
    fix_bs: false
    is_training: false
    name: RatioSampler
    scales:
    - - 128
      - 32
Global:
  cal_metric_during_train: true
  character_dict_path: /home/resources/gch/2_charsets/2_group/gch/C_all___id_50/charset.txt
  checkpoints: null
  device: gpu
  distributed: false
  epoch_num: 5
  eval_batch_step:
  - 0
  - 5000000000000
  eval_epoch_step:
  - 0
  - 100000000000
  grad_clip_val: 5.0
  grapheme_dict_path: /home/resources/gch/2_charsets/2_group/gch/G_all___id_51/charset.txt
  infer_img: null
  log_smooth_window: 50
  max_text_length: 25
  output_dir: /home/resources/gch/4_work/5_svtr2_smtr_gtc_rctc___q_head___pre_t___e5/1_C___id_82/train___id_1/config.py/../20260410_062013
  pretrained_model: /home/resources/gch/4_work/5_svtr2_smtr_gtc_rctc___q_head___pre_t___e5/1_C___id_82/train___id_1/weights/pretrained.pth
  print_batch_step: 100
  save_epoch_step:
  - 0
  - 1
  save_res_path: /home/resources/gch/4_work/5_svtr2_smtr_gtc_rctc___q_head___pre_t___e5/1_C___id_82/train___id_1/config.py/../20260410_062013/output/res.txt
  use_amp: true
  use_space_char: false
  use_tensorboard: true
  weights_dir: /home/resources/gch/4_work/5_svtr2_smtr_gtc_rctc___q_head___pre_t___e5/1_C___id_82/train___id_1/config.py/../weights
LRScheduler:
  cycle_momentum: false
  name: OneCycleLR
  warmup_epoch: 1.5
Loss:
  c_loss:
    ctc_loss:
      head_weight: 0.95
      infer_quality: false
      inner_loss:
        name: CTCLoss
      name: QualityWrapperLoss
      quality_weight: 0.05
    ctc_weight: 0.1
    gtc_loss:
      name: SMTRLoss
    gtc_weight: 1.0
    name: GTCLoss
  c_weight: 1.0
  g_loss:
    ctc_loss:
      head_weight: 0.95
      infer_quality: false
      inner_loss:
        name: CTCLoss
      name: QualityWrapperLoss
      quality_weight: 0.05
    ctc_weight: 0.1
    gtc_loss:
      name: SMTRLoss
    gtc_weight: 1.0
    name: GTCLoss
  g_weight: 1.0
  name: GCHLoss
  use_c: true
  use_g: false
Metric:
  c_metric:
    ctc_metric:
      infer_quality: false
      inner_metric:
        name: RecMetric
      name: QualityWrapperMetric
    gtc_metric:
      name: RecMetric
    is_filter: false
    main_indicator: acc
    name: RecGTCMetric
  e_metric:
    is_filter: false
    main_indicator: acc
    name: RecMetric
  g_metric:
    ctc_metric:
      infer_quality: false
      inner_metric:
        name: RecMetric
      name: QualityWrapperMetric
    gtc_metric:
      name: RecMetric
    is_filter: false
    main_indicator: acc
    name: RecGTCMetric
  name: RecGCHMetric
  use_c: true
  use_e: false
  use_g: false
Optimizer:
  filter_bias_and_bn: true
  lr: 0.000325
  name: AdamW
  weight_decay: 0.05
PostProcess:
  c_postprocess:
    character_dict_path: /home/resources/gch/2_charsets/2_group/gch/C_all___id_50/charset.txt
    ctc_label_decode:
      infer_quality: false
      inner_postprocess:
        name: CTCLabelDecode
      name: QualityWrapperPostProcess
    gtc_label_decode:
      name: SMTRLabelDecode
      next_mode: true
    name: GTCLabelDecode
    use_space_char: false
  g_postprocess:
    character_dict_path: /home/resources/gch/2_charsets/2_group/gch/G_all___id_51/charset.txt
    ctc_label_decode:
      infer_quality: false
      inner_postprocess:
        name: CTCLabelDecode
      name: QualityWrapperPostProcess
    gtc_label_decode:
      name: SMTRLabelDecode
      next_mode: true
    name: GTCLabelDecode
    use_space_char: false
  name: GCHPostProcess
  use_c: true
  use_g: false
Train:
  dataset:
    data_dir_list:
    - /home/resources/shared_datasets/STR/aihub_rec
    ds_width: true
    label_file_list:
    - /home/resources/gch/1_datasets/1_AIHUB/2_split_horizontal_clean_80:10:10/1_train/1_main___id_14/label.txt
    name: SimpleDatasetTVResize
    padding: false
    transforms:
    - DecodeImagePIL:
        img_mode: RGB
    - PARSeqAugPIL: null
    - GCHLabelEncode:
        c_encoder:
          character_dict_path: /home/resources/gch/2_charsets/2_group/gch/C_all___id_50/charset.txt
          ctc_label_encode:
            inner_encoder:
              name: CTCLabelEncode
            name: QualityWrapperHeadLabelEncode
          gtc_label_encode:
            name: SMTRLabelEncode
            sub_str_len: 5
          lower: true
          max_text_length: 25
          name: GTCLabelEncode
          use_space_char: false
        g_encoder:
          character_dict_path: /home/resources/gch/2_charsets/2_group/gch/G_all___id_51/charset.txt
          ctc_label_encode:
            inner_encoder:
              name: CTCLabelEncode
            name: QualityWrapperHeadLabelEncode
          gtc_label_encode:
            name: SMTRLabelEncode
            sub_str_len: 15
          lower: true
          max_text_length: 75
          name: GTCLabelEncode
          use_space_char: false
        use_c: true
        use_g: true
    - HierarchyKeepKeys:
        keep_keys:
          c_label:
            ctc_label:
              inner_label:
                label: null
                length: null
              quality_label: null
            gtc_label:
              label: null
              label_next: null
              label_next_pre: null
              label_subs: null
              label_subs_pre: null
              length: null
              length_subs: null
              length_subs_pre: null
          g_label:
            ctc_label:
              inner_label:
                label: null
                length: null
              quality_label: null
            gtc_label:
              label: null
              label_next: null
              label_next_pre: null
              label_subs: null
              label_subs_pre: null
              length: null
              length_subs: null
              length_subs_pre: null
          image: null
  loader:
    batch_size_per_card: 128
    drop_last: true
    max_ratio: 12
    num_workers: 12
    shuffle: true
  sampler:
    divided_factor:
    - 4
    - 16
    first_bs: 128
    fix_bs: false
    is_training: true
    name: RatioSampler
    scales:
    - - 128
      - 32
Wandb:
  name: '82'
  project: OpenOCR-GCH
  sync_tensorboard: true
eval: true
local_rank: null
